version: '3.9'

services:
  postgis14:
    image: kartoza/postgis:14-3.3--v2022.07.22
    restart: always
    environment:
      POSTGRES_DBNAME: nestjs_assignment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
  nestjs: 
    env_file: "./.env"
    restart: always
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: namhoang1604/nestjs-assignment:0.1-2022.11.08
    depends_on:
      - postgis14
    ports:
      - "3000:3000"